# ????????? ????????????? ?????? ??? ??????
# H2 in-memory database ??? ??????
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.data-locations=  # ?????? ????????, ????? ?? ?????? data.sql
spring.sql.init.mode=embedded  # ??? always, ?? ????? ?????? data.sql ?? ??????
spring.sql.init.schema-locations=classpath:schema.sql

